### ISSUE TITLE
Quickstart

### ISSUE THREAD

**Issue by StefanLecho** [localstack/docs#946]
_https://docs.localstack.cloud/getting-started/quickstart/ Please ensure that you have Node.js, npm, and make installed, before trying to deploy the application with the following make command._

When I run "make deploy" on Windows with GNU Make 4.4.1 in the localstack-demo project, I'm getting this error: "make: *** [Makefile:14: deploy] Error 2"

Which version of make should I use ?

**Comment by lakkeger** [comment]
Hi @StefanLecho,
Thanks for your patience. The version shouldn't be an issue.
From the error message the issue lies around the 14th line which is `make install`, could it be that one of the tools are not available on your host?
Could you please provide the logs of your `make deploy` run? What is the output if you run `make install`?

**Comment by HarshCasper** [comment]
A new quickstart is in development here — https://github.com/localstack/docs/pull/976
